# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose the port the app runs on
EXPOSE 3000

ARG ENVIRONMENT

ENV ENVIRONMENT=${ENVIRONMENT}

# Define the command to run the app using react-scripts
CMD REACT_APP_ENVIRONMENT=${ENVIRONMENT} npm start
