org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.incremental=true
org.gradle.parallel.threads=2
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xms64m -Xmx196m -Dsun.io.useCanonCaches=false -XX:+DoEscapeAnalysis -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -noverify -Xverify:none -XX:+TieredCompilation -da