CREATE TABLE IF NOT EXISTS sewage
(
    ID INTEGER auto_increment PRIMARY KEY,
    LAST_UPDATED DATETIME,
    FACILITY_OWNER VARCHAR(255),
    SITE_ADDRESS VARCHAR(255),
    SITE_MUNICIPALITY VARCHAR(255),
    SECTOR VARCHAR(255),
    DISTRICT VARCHAR(255),
    CONTAMINANT VARCHAR(255),
    CONTAMINANT_LIMIT FLOAT,
    CONTAMINANT_UNIT VARCHAR(255),
    CONTAMINANT_MIN_RECORD FLOAT,
    CONTAMINANT_MAX_RECORD FLOAT,
    EXCEEDANCE_TYPE VARCHAR(255),
    EXCEEDANCE_START DATE,
    EXCEEDANCE_END DATE,
    EXCEEDANCE_COUNT INTEGER,
    LIMIT_FREQUENCY VARCHAR(255),
    FACILITY_ACTION VARCHAR(255),
    MINISTRY_ACTION VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS wastewater
(
    ID INTEGER auto_increment PRIMARY KEY,
    LAST_UPDATED DATETIME,
    SECTOR VARCHAR(255),
    FACILITY VARCHAR(255),
    FACILITY_MUNICIPALITY VARCHAR(255),
    COMPANY_CODE VARCHAR(255),
    SAMPLE_DATE VARCHAR(255),
    SAMPLE_COLLECTION_FREQUENCY VARCHAR(255),
    CONTROL_POINT_NAME VARCHAR(255),
    CONTROL_POINT_ID VARCHAR(255),
    PARAMETER VARCHAR(255),
    PARAMETER_VALUE FLOAT,
    PARAMETER_UNIT VARCHAR(255),
    REPORTED_PARAMETER VARCHAR(255),
    RESULT_STRUCTURE VARCHAR(255),
    COMPONENT_TYPE VARCHAR(255),
    REGULATION VARCHAR(255)
);
